### ISSUE TITLE
GIT Übung

### ISSUE THREAD

**Issue by PeterPetrel** [random-access/FlashCardsManager#20]
Wir tun mal so, als würden wir korrekt verteilt arbeiten.
Ich lasse bewusst deinen Label integration branch aus und entwickle ausgehend vom master in einem weiteren branch weiter. Freitag dann der Merge.

**Comment by random-access** [comment]
Ok klingt gut! Ich arbeite erstmal nur an den Labels und eventuell an den Performance-Sachen die wir besprochen haben.
