### ISSUE TITLE
SourceTree installieren!

### ISSUE THREAD

**Issue by PeterPetrel** [random-access/FlashCardsManager#21]
Das ist sooo klasse. Das muss einfach jeder haben um von dem dreckigen EGit (Eclipse) runterzukommen.

**Comment by random-access** [comment]
wird schwierig... siehe https://answers.atlassian.com/questions/149631/

**Comment by PeterPetrel** [comment]
Es gibt noch smartgit für linux. Ist nicht ganz so schön. Erfüllt aber auch seinen Zweck. Aber für SourceTree würde es sich sogar lohnen eine Windows VM zu installieren^^
